<?php
/**
 * Table d'équivalence des liens internes par code du pays
 *
 * Format : <code> => <texte affiché> ([$code][0]), <nom réel> ([$code][1])
 *
 * Rendu : [[<nom réel>]] ou [[<nom réel>|<texte affiché>]]
 */

$data_pays = [
 "AF" => [ "Afghanistan", "Afghanistan" ],
 "ZA" => [ "Afrique du Sud", "Afrique du Sud" ],
 "AX" => [ "Îles Åland", "Åland" ],
 "AL" => [ "Albanie", "Albanie" ],
 "DZ" => [ "Algérie", "Algérie" ],
 "DE" => [ "Allemagne", "Allemagne" ],
 "AD" => [ "Andorre", "Andorre" ],
 "AO" => [ "Angola", "Angola" ],
 "AI" => [ "Anguilla", "Anguilla" ],
 "AQ" => [ "Antarctique", "Antarctique" ],
 "AG" => [ "Antigua-et-Barbuda", "Antigua-et-Barbuda" ],
 "SA" => [ "Arabie saoudite", "Arabie saoudite" ],
 "AR" => [ "Argentine", "Argentine" ],
 "AM" => [ "Arménie", "Arménie" ],
 "AW" => [ "Aruba", "Aruba" ],
 "AU" => [ "Australie", "Australie" ],
 "AT" => [ "Autriche", "Autriche" ],
 "AZ" => [ "Azerbaïdjan", "Azerbaïdjan" ],
 "BS" => [ "Bahamas", "Bahamas" ],
 "BH" => [ "Bahreïn", "Bahreïn" ],
 "BD" => [ "Bangladesh", "Bangladesh" ],
 "BB" => [ "Barbade", "Barbade" ],
 "BY" => [ "Biélorussie", "Biélorussie" ],
 "BE" => [ "Belgique", "Belgique" ],
 "BZ" => [ "Belize", "Belize" ],
 "BJ" => [ "Bénin", "Bénin" ],
 "BM" => [ "Bermudes", "Bermudes" ],
 "BT" => [ "Bhoutan", "Bhoutan" ],
 "BO" => [ "Bolivie", "Bolivie" ],
 "BQ" => [ "Pays-Bas caribéens", "Pays-Bas caribéens" ],
 "BA" => [ "Bosnie-Herzégovine", "Bosnie-Herzégovine" ],
 "BW" => [ "Botswana", "Botswana" ],
 "BV" => [ "Île Bouvet", "Île Bouvet" ],
 "BR" => [ "Brésil", "Brésil" ],
 "BN" => [ "Brunei", "Brunei" ],
 "BG" => [ "Bulgarie", "Bulgarie" ],
 "BF" => [ "Burkina Faso", "Burkina Faso" ],
 "BI" => [ "Burundi", "Burundi" ],
 "KY" => [ "Îles Caïmans", "Îles Caïmans" ],
 "KH" => [ "Cambodge", "Cambodge" ],
 "CM" => [ "Cameroun", "Cameroun" ],
 "CA" => [ "Canada", "Canada" ],
 "CV" => [ "Cap-Vert", "Cap-Vert" ],
 "CF" => [ "République centrafricaine", "République centrafricaine" ],
 "CL" => [ "Chili", "Chili" ],
 "CN" => [ "Chine", "Chine" ],
 "CX" => [ "Île Christmas", "Île Christmas (Australie)" ],
 "CY" => [ "Chypre", "Chypre (pays)" ],
 "CC" => [ "Îles Cocos", "Îles Cocos" ],
 "CO" => [ "Colombie", "Colombie" ],
 "KM" => [ "Comores", "Comores (pays)" ],
 "CG" => [ "République du Congo", "République du Congo" ],
 "CD" => [ "République démocratique du Congo", "République démocratique du Congo" ],
 "CK" => [ "Îles Cook", "Îles Cook" ],
 "KR" => [ "Corée du Sud", "Corée du Sud" ],
 "KP" => [ "Corée du Nord", "Corée du Nord" ],
 "CR" => [ "Costa Rica", "Costa Rica" ],
 "CI" => [ "Côte d&#39;Ivoire", "Côte d&#39;Ivoire" ],
 "HR" => [ "Croatie", "Croatie" ],
 "CU" => [ "Cuba", "Cuba" ],
 "CW" => [ "Curaçao", "Curaçao" ],
 "DK" => [ "Danemark", "Danemark" ],
 "DJ" => [ "Djibouti", "Djibouti" ],
 "DO" => [ "République dominicaine", "République dominicaine" ],
 "DM" => [ "Dominique", "Dominique (pays)" ],
 "EG" => [ "Égypte", "Égypte" ],
 "SV" => [ "Salvador", "Salvador" ],
 "AE" => [ "Émirats arabes unis", "Émirats arabes unis" ],
 "EC" => [ "Équateur", "Équateur (pays)" ],
 "ER" => [ "Érythrée", "Érythrée" ],
 "ES" => [ "Espagne", "Espagne" ],
 "EE" => [ "Estonie", "Estonie" ],
 "US" => [ "États-Unis", "États-Unis" ],
 "ET" => [ "Éthiopie", "Éthiopie" ],
 "FK" => [ "Malouines", "Îles Malouines" ],
 "FO" => [ "Îles Féroé", "Îles Féroé" ],
 "FJ" => [ "Fidji", "Fidji" ],
 "FI" => [ "Finlande", "Finlande" ],
 "FR" => [ "France", "France" ],
 "GA" => [ "Gabon", "Gabon" ],
 "GM" => [ "Gambie", "Gambie" ],
 "GE" => [ "Géorgie", "Géorgie (pays)" ],
 "GS" => [ "Géorgie du Sud-et-les îles Sandwich du Sud", "Géorgie du Sud-et-les îles Sandwich du Sud" ],
 "GH" => [ "Ghana", "Ghana" ],
 "GI" => [ "Gibraltar", "Gibraltar" ],
 "GR" => [ "Grèce", "Grèce" ],
 "GD" => [ "Grenade", "Grenade (pays)" ],
 "GL" => [ "Groenland", "Groenland" ],
 "GP" => [ "Guadeloupe", "Guadeloupe" ],
 "GU" => [ "Guam", "Guam" ],
 "GT" => [ "Guatemala", "Guatemala" ],
 "GG" => [ "Guernesey", "Bailliage de Guernesey" ],
 "GN" => [ "Guinée", "Guinée" ],
 "GW" => [ "Guinée-Bissau", "Guinée-Bissau" ],
 "GQ" => [ "Guinée équatoriale", "Guinée équatoriale" ],
 "GY" => [ "Guyana", "Guyana" ],
 "GF" => [ "Guyane", "Guyane" ],
 "HT" => [ "Haïti", "Haïti" ],
 "HM" => [ "Îles Heard-et-MacDonald", "Îles Heard-et-MacDonald" ],
 "HN" => [ "Honduras", "Honduras" ],
 "HK" => [ "Hong Kong", "Hong Kong" ],
 "HU" => [ "Hongrie", "Hongrie" ],
 "IM" => [ "Île de Man", "Île de Man" ],
 "UM" => [ "Îles mineures éloignées des États-Unis", "Îles mineures éloignées des États-Unis" ],
 "VG" => [ "Îles Vierges britanniques", "Îles Vierges britanniques" ],
 "VI" => [ "Îles Vierges des États-Unis", "Îles Vierges des États-Unis" ],
 "IN" => [ "Inde", "Inde" ],
 "ID" => [ "Indonésie", "Indonésie" ],
 "IR" => [ "Iran", "Iran" ],
 "IQ" => [ "Irak", "Irak" ],
 "IE" => [ "Irlande", "Irlande (pays)" ],
 "IS" => [ "Islande", "Islande" ],
 "IL" => [ "Israël", "Israël" ],
 "IT" => [ "Italie", "Italie" ],
 "JM" => [ "Jamaïque", "Jamaïque" ],
 "JP" => [ "Japon", "Japon" ],
 "JE" => [ "Jersey", "Jersey" ],
 "JO" => [ "Jordanie", "Jordanie" ],
 "KZ" => [ "Kazakhstan", "Kazakhstan" ],
 "KE" => [ "Kenya", "Kenya" ],
 "KG" => [ "Kirghizistan", "Kirghizistan" ],
 "KI" => [ "Kiribati", "Kiribati" ],
 "KW" => [ "Koweït", "Koweït" ],
 "LA" => [ "Laos", "Laos" ],
 "LS" => [ "Lesotho", "Lesotho" ],
 "LV" => [ "Lettonie", "Lettonie" ],
 "LB" => [ "Liban", "Liban" ],
 "LR" => [ "Liberia", "Liberia" ],
 "LY" => [ "Libye", "Libye" ],
 "LI" => [ "Liechtenstein", "Liechtenstein" ],
 "LT" => [ "Lituanie", "Lituanie" ],
 "LU" => [ "Luxembourg", "Luxembourg" ],
 "MO" => [ "Macao", "Macao" ],
 "MK" => [ "Macédoine du Nord", "Macédoine du Nord" ],
 "MG" => [ "Madagascar", "Madagascar" ],
 "MY" => [ "Malaisie", "Malaisie" ],
 "MW" => [ "Malawi", "Malawi" ],
 "MV" => [ "Maldives", "Maldives" ],
 "ML" => [ "Mali", "Mali" ],
 "MT" => [ "Malte", "Malte" ],
 "MP" => [ "Îles Mariannes du Nord", "Îles Mariannes du Nord" ],
 "MA" => [ "Maroc", "Maroc" ],
 "MH" => [ "Îles Marshall", "Îles Marshall" ],
 "MQ" => [ "Martinique", "Martinique" ],
 "MU" => [ "Maurice", "Maurice (pays)" ],
 "MR" => [ "Mauritanie", "Mauritanie" ],
 "YT" => [ "Mayotte", "Mayotte" ],
 "MX" => [ "Mexique", "Mexique" ],
 "FM" => [ "États fédérés de Micronésie", "États fédérés de Micronésie" ],
 "MD" => [ "Moldavie", "Moldavie" ],
 "MC" => [ "Monaco", "Monaco" ],
 "MN" => [ "Mongolie", "Mongolie" ],
 "ME" => [ "Monténégro", "Monténégro" ],
 "MS" => [ "Montserrat", "Montserrat (Antilles)" ],
 "MZ" => [ "Mozambique", "Mozambique" ],
 "MM" => [ "Birmanie", "Birmanie" ],
 "NA" => [ "Namibie", "Namibie" ],
 "NR" => [ "Nauru", "Nauru" ],
 "NP" => [ "Népal", "Népal" ],
 "NI" => [ "Nicaragua", "Nicaragua" ],
 "NE" => [ "Niger", "Niger" ],
 "NG" => [ "Nigeria", "Nigeria" ],
 "NU" => [ "Niue", "Niue" ],
 "NF" => [ "Île Norfolk", "Île Norfolk" ],
 "NO" => [ "Norvège", "Norvège" ],
 "NC" => [ "Nouvelle-Calédonie", "Nouvelle-Calédonie" ],
 "NZ" => [ "Nouvelle-Zélande", "Nouvelle-Zélande" ],
 "IO" => [ "Territoire britannique de l'océan Indien", "Territoire britannique de l&#39;océan Indien" ],
 "OM" => [ "Oman", "Oman" ],
 "UG" => [ "Ouganda", "Ouganda" ],
 "UZ" => [ "Ouzbékistan", "Ouzbékistan" ],
 "PK" => [ "Pakistan", "Pakistan" ],
 "PW" => [ "Palaos", "Palaos" ],
 "PS" => [ "Palestine", "Palestine (État)" ],
 "PA" => [ "Panama", "Panama" ],
 "PG" => [ "Papouasie-Nouvelle-Guinée", "Papouasie-Nouvelle-Guinée" ],
 "PY" => [ "Paraguay", "Paraguay" ],
 "NL" => [ "Pays-Bas", "Pays-Bas" ],
 "PE" => [ "Pérou", "Pérou" ],
 "PH" => [ "Philippines", "Philippines" ],
 "PN" => [ "Îles Pitcairn", "Îles Pitcairn" ],
 "PL" => [ "Pologne", "Pologne" ],
 "PF" => [ "Polynésie française", "Polynésie française" ],
 "PR" => [ "Porto Rico", "Porto Rico" ],
 "PT" => [ "Portugal", "Portugal" ],
 "QA" => [ "Qatar", "Qatar" ],
 "RE" => [ "La Réunion", "La Réunion" ],
 "RO" => [ "Roumanie", "Roumanie" ],
 "GB" => [ "Royaume-Uni", "Royaume-Uni" ],
 "RU" => [ "Russie", "Russie" ],
 "RW" => [ "Rwanda", "Rwanda" ],
 "EH" => [ "République arabe sahraouie démocratique", "République arabe sahraouie démocratique" ],
 "BL" => [ "Saint-Barthélemy", "Saint-Barthélemy (Antilles françaises)" ],
 "KN" => [ "Saint-Christophe-et-Niévès", "Saint-Christophe-et-Niévès" ],
 "SM" => [ "Saint-Marin", "Saint-Marin" ],
 "MF" => [ "Saint-Martin", "Saint-Martin (Antilles françaises)" ],
 "SX" => [ "Saint-Martin", "Saint-Martin (royaume des Pays-Bas)" ],
 "PM" => [ "Saint-Pierre-et-Miquelon", "Saint-Pierre-et-Miquelon" ],
 "VA" => [ "État de la Cité du Vatican", "Vatican" ],
 "VC" => [ "Saint-Vincent-et-les-Grenadines", "Saint-Vincent-et-les-Grenadines" ],
 "SH" => [ "Sainte-Hélène, Ascension et Tristan da Cunha", "Sainte-Hélène, Ascension et Tristan da Cunha" ],
 "LC" => [ "Sainte-Lucie", "Sainte-Lucie" ],
 "SB" => [ "Îles Salomon", "Îles Salomon" ],
 "WS" => [ "Samoa", "Samoa" ],
 "AS" => [ "Samoa américaines", "Samoa américaines" ],
 "ST" => [ "Sao Tomé-et-Principe", "Sao Tomé-et-Principe" ],
 "SN" => [ "Sénégal", "Sénégal" ],
 "RS" => [ "Serbie", "Serbie" ],
 "SC" => [ "Seychelles", "Seychelles" ],
 "SL" => [ "Sierra Leone", "Sierra Leone" ],
 "SG" => [ "Singapour", "Singapour" ],
 "SK" => [ "Slovaquie", "Slovaquie" ],
 "SI" => [ "Slovénie", "Slovénie" ],
 "SO" => [ "Somalie", "Somalie" ],
 "SD" => [ "Soudan", "Soudan" ],
 "SS" => [ "Soudan du Sud", "Soudan du Sud" ],
 "LK" => [ "Sri Lanka", "Sri Lanka" ],
 "SE" => [ "Suède", "Suède" ],
 "CH" => [ "Suisse", "Suisse" ],
 "SR" => [ "Suriname", "Suriname" ],
 "SJ" => [ "Svalbard et ile Jan Mayen", "Norvège" ],
 "SZ" => [ "Eswatini", "Eswatini" ],
 "SY" => [ "Syrie", "Syrie" ],
 "TJ" => [ "Tadjikistan", "Tadjikistan" ],
 "TW" => [ "Taïwan", "République de Chine (Taïwan)" ],
 "TZ" => [ "Tanzanie", "Tanzanie" ],
 "TD" => [ "Tchad", "Tchad" ],
 "CZ" => [ "Tchéquie", "Tchéquie" ],
 "TF" => [ "Terres australes et antarctiques françaises", "Terres australes et antarctiques françaises" ],
 "TH" => [ "Thaïlande", "Thaïlande" ],
 "TL" => [ "Timor oriental", "Timor oriental" ],
 "TG" => [ "Togo", "Togo" ],
 "TK" => [ "Tokelau", "Tokelau" ],
 "TO" => [ "Tonga", "Tonga" ],
 "TT" => [ "Trinité-et-Tobago", "Trinité-et-Tobago" ],
 "TN" => [ "Tunisie", "Tunisie" ],
 "TM" => [ "Turkménistan", "Turkménistan" ],
 "TC" => [ "Îles Turques-et-Caïques", "Îles Turques-et-Caïques" ],
 "TR" => [ "Turquie", "Turquie" ],
 "TV" => [ "Tuvalu", "Tuvalu" ],
 "UA" => [ "Ukraine", "Ukraine" ],
 "UY" => [ "Uruguay", "Uruguay" ],
 "VU" => [ "Vanuatu", "Vanuatu" ],
 "VE" => [ "Venezuela", "Venezuela" ],
 "VN" => [ "Viêt Nam", "Viêt Nam" ],
 "WF" => [ "Wallis-et-Futuna", "Wallis-et-Futuna" ],
 "YE" => [ "Yémen", "Yémen" ],
 "ZM" => [ "Zambie", "Zambie" ],
 "ZW" => [ "Zimbabwe", "Zimbabwe" ],
];

/**
 * Retourne le lien interne d'un pays à partir de son code.
 *
 * @param string $code Le code du pays.
 * @param bool $nom Détermine si on retourne <texte affiché>.
 * @return string Formation du lien interne selon la valeur de $nom.
 */
function data_pays_code($code, $nom=false) {
  global $data_pays;
  
  // Vérifie si le code du pays existe dans le tableau des données
  if (!isset($data_pays[$code])) {
    return "$code"; // Retourne le code lui-même si le code n'existe pas
  }
  
  // Si $nom est true, retourne <texte affiché>
  if ($nom) {
    return $data_pays[$code][0];
  } else {
    // Vérifie si <nom réel> de l'article diffère de <texte affiché>
    if ($data_pays[$code][1] != $data_pays[$code][0]) {
      // True: Retourne [[<nom réel>|<texte affiché>]]
      return "[[" . $data_pays[$code][1] . "|" . $data_pays[$code][0] . "]]";
    } else {
      // Else: Retourne [[<nom réel>]]
      return "[[" . $data_pays[$code][1] . "]]";
    }
  }
}

